package com.elt.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LeaveApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String leaveApplicationStatus;
	private java.lang.Integer leaveBalance;
	private java.lang.Integer leaveId;
	private java.lang.String leaveType;
	private java.lang.Integer noOfYearsInCompany;
	private java.lang.Integer totalNoOfLeavesApplied;

	public LeaveApplication() {
	}

	public java.lang.String getLeaveApplicationStatus() {
		return this.leaveApplicationStatus;
	}

	public void setLeaveApplicationStatus(
			java.lang.String leaveApplicationStatus) {
		this.leaveApplicationStatus = leaveApplicationStatus;
	}

	public java.lang.Integer getLeaveBalance() {
		return this.leaveBalance;
	}

	public void setLeaveBalance(java.lang.Integer leaveBalance) {
		this.leaveBalance = leaveBalance;
	}

	public java.lang.Integer getLeaveId() {
		return this.leaveId;
	}

	public void setLeaveId(java.lang.Integer leaveId) {
		this.leaveId = leaveId;
	}

	public java.lang.String getLeaveType() {
		return this.leaveType;
	}

	public void setLeaveType(java.lang.String leaveType) {
		this.leaveType = leaveType;
	}

	public java.lang.Integer getNoOfYearsInCompany() {
		return this.noOfYearsInCompany;
	}

	public void setNoOfYearsInCompany(java.lang.Integer noOfYearsInCompany) {
		this.noOfYearsInCompany = noOfYearsInCompany;
	}

	public java.lang.Integer getTotalNoOfLeavesApplied() {
		return this.totalNoOfLeavesApplied;
	}

	public void setTotalNoOfLeavesApplied(
			java.lang.Integer totalNoOfLeavesApplied) {
		this.totalNoOfLeavesApplied = totalNoOfLeavesApplied;
	}

	public LeaveApplication(java.lang.String leaveApplicationStatus,
			java.lang.Integer leaveBalance, java.lang.Integer leaveId,
			java.lang.String leaveType, java.lang.Integer noOfYearsInCompany,
			java.lang.Integer totalNoOfLeavesApplied) {
		this.leaveApplicationStatus = leaveApplicationStatus;
		this.leaveBalance = leaveBalance;
		this.leaveId = leaveId;
		this.leaveType = leaveType;
		this.noOfYearsInCompany = noOfYearsInCompany;
		this.totalNoOfLeavesApplied = totalNoOfLeavesApplied;
	}

}